export default {
  signIn: '/',
  recover: '/recover',
  requestTrip: '/find-trip',
  myTrips: '/my-trips',
  createTrip: '/create-trip',
  profile: '/profile',
  updateUser: '/profile/edit',
  signUp: '/sign-up',
  addStops: '/add-stops',
  requestedTrip: '/requested-trip',
  passengerTrips: '/passenger-trips',
  myTripDetails: '/my-trips/:id',
  currentTrip: '/progress/:id',
}
